### PR TITLE
Add header to map

### PR DESCRIPTION
**Pull request by alexelash**
## Overview
This PR separates app-level content (title, about and contact links) to a separate header bar. This is to clear up the controls in the filter pane, and to make app-level info more prominent on desktop.

## Demo
screen shot 2019-01-27 at 4 55 33 pm
screen shot 2019-01-27 at 4 55 42 pm

## Notes
- I added a doctype to the HTML
- I changed some classnames to use the BEM naming conventions, which will hopefully make it a bit easier to navigate the CSS.
- I started trying to check it out in different browsers, and noticed that the map doesn't seem to load in IE or Edge. IE11 looks like the CSS isn't loading, while Edge's CSS seems to load what I could see of Edge's looked okay.

### CODE REVIEW

**Review by pcaisse — COMMENTED** [review]
So I like the idea of there being a header to anchor the page (not just widgets floating around in space). It makes it feel more like a web site than just a data mashup. That said, the design feels a little off to me:
lang_map_header

It seems like it's not longer super clear that the filters are where you should look and that's what you should interact with. It seems like the filters should maybe be inside the header or there should be more stuff in there. On my home laptop, the bar is really long and rather empty. Maybe the filters widget should be labeled "Filters"?

I also noticed that hamburger icon doesn't seem to be working for me on mobile (no longer does anything when tapped):
lang_map_header_mobile


The hamburger icon also feels a little off since it's not in the header anymore. It seems that with other mobile apps the hamburger icon is always in the top left or right corner, and it feels a little strange to me that here that isn't the case.

What do you think?

**Comment by alexelash** [comment]
@pcaisse —
Header bar:
- One thing we could do to combat the empty space is to take a centered approach, since there are so few links up at the top. Something like: 
screen shot 2019-01-30 at 9 12 51 pm
I could also add some more vertical height to the header bar to make it feel slightly less long. Retaining the current left-aligned approach (which is fairly common). What do you think of these potential solutions?

Filters:
- Sure! That's a good idea. 

Hamburger icon:
- **Iconography in this new context**
Absolutely. That's a great catch, it no longer makes sense here. What we can do is retain the previously established UI (more/less) and get rid of the hamburger/x interaction. How does that sound?
- **Not working**
🙈Oh, shoot, sorry for breaking that! I'll look at it again. I'm guessing it's bc of a changed ID that I didn't notice. I'll check through the rest of the interactions as well to make sure they're def working.

**Comment by pcaisse** [comment]
I like the idea of centering the title but could also see left-aligning it. I wouldn't mind adding some more links which could work well to fill up some of that space. I think a FAQ (could just be another modal) might be nice as well as a "Report an Issue" link for bug reports. Maybe even a user guide with gifs that show how to use the app?

Re: hamburger icon, I'm not sure how it should work... I think it's important to be able to toggle a view where all filters are hidden and just show the header since space is at a premium on mobile depending on device size and you want to have enough screen real estate to be able to navigate around the map. Maybe the toggle icon/button/text would need to live inside the header.

While we're considering redesigns, would it make sense to do a left sidebar for the filters/legend instead of floating widgets? It might make sense to have a left bar that's hideable. It would have to be adapted for mobile devices as well. Not sure if that's biting off more than we can chew...

**Comment by alexelash** [comment]
Cool, more links (so long as you think they'll be useful, of course) would definitely help make the links more noticeable! I'll play with increasing the font size of the links and logotype as well, see if that's helpful.

Ah, gotcha. Yeah, might make sense then to have a filter icon that toggles the filters in the header bar on mobile, next to the hamburger icon that shows the main navigation. I've definitely seen that before...

... but I do like the idea of a sidebar. I think that that might solve more of our problems. I'll mock something up and do a little research to see if one (sidebar vs. floating filters) is better than the other.

**Comment by alexelash** [comment]
Ready for another look! I updated classnames to use BEM naming conventions and we've got ourselves a sidebar.

Not perfect mobile experience. I think that it would be nice if only the filters pane or the navigation were open at a time.

## Demo:
Desktop
screen shot 2019-02-16 at 6 05 22 pm

Mobile
screen shot 2019-02-16 at 6 05 05 pm
screen shot 2019-02-16 at 6 04 59 pm
screen shot 2019-02-16 at 6 05 08 pm

**Comment by pcaisse** [comment]
So, I love it. However, on my phone, which admittedly is old and small, I can't see the legend button:
screenshot_20190219-194624_chrome
I assume it's because of the header content wrapping unexpectedly. Is that an easy fix?

**Comment by pcaisse** [comment]
The only other thing I noticed is that on mobile the filters always show up first and always occupy the whole screen. This could be bewildering the first time that you come to the page (I could see the user wondering "Where's the map?"). Maybe this isn't a big deal and we just punt on it for now.

**Comment by pcaisse** [comment]
Merging and will create an issue for the one issue with small screens on mobile.

**Pull request merged**
